### ISSUE TITLE
Ability to flag posts

### ISSUE THREAD

**Issue by sebwalk** [strawpoll/strawpoll#10]
Hey Dan,
maybe add a feature where you could flag posts for different reasons.
Would maybe look like this:
1. Click on "Flag as Inappropriate"
2. Select category (Pornographic, Dangerous, Insulting, Spam, Infringement of Copyright)
3. You (and maybe some others, I would be happy to help) go into your quickly-to-use interface and approve the flag claims. At the click of a button a post would either be deleted or the flag would be removed.

I hope this idea helps you,
Sebastian Walker

**Comment by dandirks** [comment]
Thanks for the suggestion. I plan to have some mechanism for flagging polls in the next release.

**Comment by dandirks** [comment]
I have completed the work on my dev instance to show a link to report abuse of the ToS in the footer of every page. There may need to be some additional work done here in the future, but I believe this will suffice for the time being.

The report abuse form will be live with the next release of Straw Poll. I am closing this issue so I have a better handle on what is still left to be done. Thanks for the help.
