### ISSUE TITLE
Single Transferable Vote System?

### ISSUE THREAD

**Issue by Fechulo** [strawpoll/strawpoll#14]
I assume you know what S.T.V. is but just in case: https://www.youtube.com/watch?v=l8XOZJkozfI
I think it would be awesome if you could choose what system to use when setting up a poll.

**Comment by dandirks** [comment]
Thanks for the suggestion. I think I will roll this issue into issue #4, where I will investigate adding multiple new voting systems to the current implementation.

**Comment by Fechulo** [comment]
Awesome, thanks!
