### ISSUE TITLE
Cannot sign in on strawpoll with captcha

### ISSUE THREAD

**Issue by atenfyr** [strawpoll/strawpoll#20]
If a strawpoll has a captcha on it and you try to click the "Sign in" button on that page, it fails to do such.
Try visiting http://beta.strawpoll.me/atenefyr/2, signing out, and attempting to sign in. You just see a screen with no google button, and you have to reload the page.

However, visiting http://beta.strawpoll.me/atenefyr/1, signing out, and signing in works fine, because that poll does not have a captcha.

**Comment by dandirks** [comment]
Ah, that's a curious one. I think I know what's going on, but I didn't
realize those two components would cause that interaction. I'll get it
fixed tonight.

Thanks for the bug report! I appreciate it greatly.

**Comment by dandirks** [comment]
This should now be fixed on beta. Thanks for the help.
