### ISSUE TITLE
Drop down error menu 

### ISSUE THREAD

**Issue by intronate67** [strawpoll/strawpoll#22]
When users try to create a post but forget information like the title, the page just does nothing. It should let the user know what they haven't included even though they should already know. It would just be nice.
Maybe even if the division that contains the main poll had a subtle shack like what Mac OSX does sometimes.

**Comment by dandirks** [comment]
Did you see this issue on the beta (http://beta.strawpoll.me/), or on the main site (http://strawpoll.me/)? 

If you saw it on the beta, I mistakenly changed something that broke the error messages from displaying correctly and it should be fixed. If you saw it on the main site, the error messaging will be coming with the next version of Straw Poll (which is currently on the beta site). :)

**Comment by intronate67** [comment]
I saw the issue on the beta site but now checking it I cant see it.
