### ISSUE TITLE
Add another one???

### ISSUE THREAD

**Issue by mayorjenn** [strawpoll/strawpoll#24]
So I wanted to make a survey for my followers to answer to see what they were looking for. While I was at it, I chose to test the beta for the next version! Now then, I had four options which previously would have worked however no matter how many options I filled in it said please enter a poll question thingy. Anybody else get this issue?

**Comment by dandirks** [comment]
Did you only fill in options without a question? Polls should always
require a question to be filled out, both on beta and production. Beta is
just more verbose about telling you the error.
