### ISSUE TITLE
[SUGGESTION] Proxy Checker Option

### ISSUE THREAD

**Issue by unix-system** [strawpoll/strawpoll#28]
This option should be automatically ticked, and would mean that all IPs trying to vote are put through some proxy checkers, to see if they are proxies or not. This will stop vote tampering.

**Comment by dandirks** [comment]
Thanks for the suggestion, but the proxy checking will happen by default. The next version will have better support for determining tampering, from CAPTCHA to some behind-the-scenes stuff in the pipeline. However, I don't think I will ever add an option to disable the proxy checking at this time, and it will be on for everyone.
