### ISSUE TITLE
Better error messaging for poll creation

### ISSUE THREAD

**Issue by gandalfx** [strawpoll/strawpoll#3]
Right now on strawpoll.me I can't create a new poll. To be precise, the submit button (“Create Poll”) doesn't seem to react at all. Everything else works fine, I can enter options, new lines appear automatically etc.

I tried it in Firefox 38 (with lots of privacy plugins) and Vivalid (bare installation). Somebody else confirmed it for Chrome.

**Comment by dandirks** [comment]
Just to verify, you are putting in a title and at least two options to the
poll, correct?

**Comment by gandalfx** [comment]
Well of course I didn't. I missed that the title/question is obligatory. I'm an idiot.

On the other hand at least two other people I talked to on IRC missed it as well. Maybe you could make the UI give a little more feedback then just not doing anything in case something is missing. Maybe a little animation to highlight the empty fields. Or, alternatively, make the title/question optional.

Anyway, thanks for the hint and keep up the great work. Strawpoll is pretty awesome! ;)
Cheers

**Comment by dandirks** [comment]
Ahh, okay. Don't feel bad, you are not the first that has had that same
issue. :)

Better messaging will definitely be part of the next release. Thanks for
the report.

**Comment by sebwalk** [comment]
Good idea!

**Comment by dandirks** [comment]
There are now informative error messages on my development version of Straw Poll. They will be visible in the next version of Straw Poll. Closing this issue for now so I can better keep track of what is left to be done. Thanks for the help.
