### ISSUE TITLE
Canno't create new strawpolls using API

### ISSUE THREAD

**Issue by ghost** [strawpoll/strawpoll#32]
Here's my request
![Request](http://fubz.ga/903)

in documentation i need to make POST request https://strawpoll.me/api/v2/polls with title and options required values.

EDIT:
I tired with content-type header too. Doesn't work anyway
![Screenshot](http://fubz.ga/904)

**Comment by dandirks** [comment]
From what I can tell from your screenshot, you are submitting the data as a URL-encoded form submission. That is invalid. The poll data needs to be submitted as a JSON post body. I am unsure as to how to do that in the particular tool that you are using, but I assume there must be a way.
