### ISSUE TITLE
Results Not Updating Live

### ISSUE THREAD

**Issue by ToggleSwitch106** [strawpoll/strawpoll#40]
When I create a strawpoll and go to the results, they do not live update. I have to refresh the page to get it to reload the numbers. I've tried on multiple browsers and they all do the same thing.

**Comment by ToggleSwitch106** [comment]
After watching a stream and keeping an eye on a strawpoll it appears to update but it updates once every 20 seconds

**Comment by dandirks** [comment]
Was it possible you were using HTTPS to access Straw Poll? There have been some architectural issues with doing full real-time over HTTPS that I was just able to solve. Therefore, HTTPS connections should now be able to stream results in real-time.

**Comment by ToggleSwitch106** [comment]
I didn't even consider that as a possible reason! I turned off my HTTPS encryption and it did start updating properly. However when it was on HTTPS it still did update slowly, if you want to know.
