### ISSUE TITLE
Being able to maliciously inject code to display on any users viewing the poll?

### ISSUE THREAD

**Issue by ghost** [strawpoll/strawpoll#46]
This happened to a very popular youtuber recently. His name is EtikaWorldNetwork. His recent smash fan ballot was hacked temporarily with code being implemented for it to flash random text and increase the votes of one option insanely and decrease the others. Please fix this and or explain what causes it to be allowed.

**Comment by dandirks** [comment]
There was a misconfiguration that was allowing users to publish updates as if it were the backend server to a given poll. This should have been graphical only, and these false updates have not been counted.

I have corrected the misconfiguration, and this should no longer be possible. Thank you for reporting this issue, and please let me know if you see it again.

**Comment by ghost** [comment]
Will do. Thanks for explaining it.
