### ISSUE TITLE
Documented API

### ISSUE THREAD

**Issue by AlessandroMinali** [strawpoll/strawpoll#5]
Doesn't need to be intense, just basically the public endpoints and how to use them

**Comment by dandirks** [comment]
Thanks for the suggestion. I have added a page to the wiki explaining the endpoints that I expect to be publicly available for consumption here:

https://github.com/dandirks/strawpoll/wiki/API

Any not listed on this page are going to change in fundamental ways that will break your application, and therefore I do not intend them for public use currently.
