### ISSUE TITLE
Get this off of here.

### ISSUE THREAD

**Issue by McFarts** [strawpoll/strawpoll#58]
You're supposed to use Github for open source software only. Stop taking advantage of the system ~

**Comment by Chewsterchew** [comment]
Uh... No..

**Comment by McFarts** [comment]
Well, then this project is not open source.  Either make the repository private, or open source your script.

**Comment by Chewsterchew** [comment]
He has it like this for people to report bugs.

**Comment by Chewsterchew** [comment]
Actually, no where in the terms does it say it to be open source software only. Please prove me wrong.

**Comment by McFarts** [comment]
Github is not the place to report bugs. It's to build software. Not to report bugs for a closed-source piece of software.

**Comment by FireSnyper** [comment]
Correct me if I'm wrong, but nowhere in the terms does it say that GitHub is to be used for ONLY open source software, or that it is not a place to report bugs. Get your facts right, McFarts.

**Comment by McFarts** [comment]
No, get your facts straight.

Github is for creating software through pull requests and developing software, not to be used as a '100% bug only report system'.

**Comment by FireSnyper** [comment]
McFarts, I think you misunderstand me. GitHub is not restricted to be used only for software creation, but it was also not designed for bug reporting. 

Since this does not violate the terms of use for GitHub, then stop being so bullish and close this issue. Don't you have better things to do?

**Comment by McFarts** [comment]
Fine, but last time I checked Github was for the creation of software. And I feel like if you have a closed source software, it cannot help achieve that (since it's closed, no one can contribute)

**Comment by Chewsterchew** [comment]
We are contributing, we use the program to find issues and report them. They get fixed, then the cycle repeats.

**Comment by baconface** [comment]
@McFarts Using just the issue manager is officially allowed by Github. They even posted [alternative uses](https://guides.github.com/features/issues/#uses) for the issue manager that include to-do lists for fixing a house and maintaining recipes. Even [JSFiddle](https://github.com/jsfiddle/jsfiddle-issues/issues) uses Github's issue manager for bug reporting.
