### ISSUE TITLE
Can't POST

### ISSUE THREAD

**Issue by TheWinuXs** [strawpoll/strawpoll#68]
Hello,
We can't POST a poll
I have tested with http://i.imgur.com/TYTib95.png and http://i.imgur.com/VctYRq4.png
and doesn't worked..

**Comment by Korkd** [comment]
Getting the same.

Empty response with a 307 temporary redirect to the same URL I'm hitting.

**Comment by Korkd** [comment]
http://www.strawpoll.me rather than http://strawpoll.me

The wiki is out of date

**Comment by TheWinuXs** [comment]
Yes I know the support answer me by email ;)
