### ISSUE TITLE
Security Measures

### ISSUE THREAD

**Issue by Paladienne** [strawpoll/strawpoll#8]
As it is it's ridiculously easy to proxyspam strawpolls, and it happens quite often.

It may not be the most user friendly measure, but you should consider adding something like reCAPTCHA to improve the security and trustworthiness of the polls.

**Comment by sebwalk** [comment]
Maybe use the new nocaptcha recaptcha so it doesnt bug the users too hard.

**Comment by dandirks** [comment]
Thanks for the suggestion. CAPTCHA support is done on my local dev instance and will be coming in the next version of Straw Poll, which is tentatively scheduled for July 4th weekend.

**Comment by dandirks** [comment]
CAPTCHA support should be complete on my development version, and will be included in the next release. Closing this issue so that I can better keep track of what needs to be done yet. Thanks for the help.
