### ISSUE TITLE
Don't direct users to chrome frame

### ISSUE THREAD

**Issue by metarmask** [strawpoll/strawpoll#9]
From ["Chromium Blog: Retiring Chrome Frame"](http://blog.chromium.org/2013/06/retiring-chrome-frame.html):

> If you are a developer with an app that points users to Chrome Frame, please prompt visitors to [upgrade to a modern browser](http://www.whatbrowser.org/). You can learn more about these changes in our [FAQ](https://developers.google.com/chrome/chrome-frame/).

**Comment by dandirks** [comment]
Whoops, I totally forgot to remove that from the warning message. Thanks for letting me know it's still there. It will be removed in the next version of Straw Poll.

**Comment by dandirks** [comment]
This is now fixed on my development version, and will be pushed to production in the next release. Thanks again for your help.
